[sources.in]
  type = "generator"
  batch_interval = 0.001
  lines = ["hello"]
  sequence = true
  format = "shuffle"

[sinks.out]
  type = "http"
  inputs = ["in"]
  compression = "none"
  healthcheck = true
  uri = "${URL}"
  encoding.codec = "json"

  request.in_flight_limit = ${VECTOR_REQUEST_IN_FLIGHT_LIMIT:-"adaptive"}
  request.rate_limit_num = 9223372036854775807 # max i64 (https://github.com/timberio/vector/issues/3499)

  buffer.max_events = 1000
  buffer.type = "memory"
  buffer.when_full = "drop_newest"

  batch.max_events = 1
